import styles from "./artifacts.module.scss";

export default function Artifacts() {
   return (
      <main className={styles.artifacts_main}>
         <h1>Quick Navigation</h1>
         <ul id="quicknav" className={styles.quicknav}>
            <li><a href="#career-aspirations">Career Aspirations</a></li>
            <li><a href="#project-management-plan">Project Management Plan</a></li>
            <li><a href="#event-report-1">Event Report</a></li>
            <li><a href="#ethical-case-study">Ethical Case Study</a></li>
            <li><a href="#information-policy-in-news">Information Policy/Technology In News</a></li>
            <li><a href="#event-report-2">Event Report 2</a></li>
            <li><a href="#program-review">Program Review</a></li>
            <li><a href="#program-review-2">Program Review 2</a></li>
            <li><a href="#reflection-essay">Reflection Essay</a></li>
         </ul>
         <h1 id="career-aspirations">Career Aspirations Essay</h1>
         <p>
            My major area of study is information science with a concentration in web development. This major is relevant to my career aspiration. My career aspiration is to become a software developer of some kind. This can be either a front-end developer or a full stack developer. I am not too particular on which one, as I enjoy both the front-end side and full stack side of the development process of web applications. This is the role I envision myself working in in my upcoming future career. The origins of how I became passionate about web development goes back to when I was in 7th grade. I took my first web design class, and I knew by taking that class I was going to do that for a career. It was a fascinating thing to make a website purely by hand and I really enjoyed the creative process that went into it as well.
         </p>
         <p>
            I do have brief work experience in web development. When I worked for Westlake Christian School, I worked alongside someone to help add content to the school&apos;s website. The school used a CMS provider called FACTS to host their website. My job was to go through the CMS and add relevant content depending on the request of my manager. My non-work experience related to web development is the various projects I have made and host the source code on my GitHub account.
         </p>
         <p>
            Prior to this assignment, I had not visited the USF career services website. However, I do find this website useful after visiting. It has a wide range of resources available for students’ seeking information or opportunities to browse. The most interesting aspect to me is the career fairs that they have going on. This is appealing because I have yet to go to one, but they do seem like a great opportunity for those who are looking to meet directly with employers and other alike minds trying to work for a company. Therefore, I do plan on attending one of these for Technology and Engineering in the future.
         </p>
         <p>
            I do have various internship experiences dating all throughout my duration at college and even high school. As mentioned, prior, I did an internship as a web developer at Westlake Christian School. I was eventually added as an employee and did database management for them for around another year until December 2023. Another internship I did was at Lockheed Martin. I completed it through a dual enrollment class my senior year of high school called the executive internship program. During my time there, I helped them with database management for parts used in the development areas, as well as organizing physical stencil boards and SMT parts. Regarding other actual jobs, I have worked at Publix as a customer service employee since 2016 when I was 14 years old, and currently still work there today. Additionally, I have also worked as an invoice specialist for Label IT technologies for over a year now. I work these two jobs simultaneously as well as attending USF.
         </p>
         <p>
            I have done a very length amount of research into the world of web application development. There are tons of resources I utilize such as W3schools, FreeCodeCamp, GeeksForGeeks, and many more. I have also taken an extensive number of notes on things such as data structures and algorithms. USF library resources have not been used often for me when it comes to researching for my career, as that usually contains more study related information, whereas I am searching for documentation and tutorials. In my time researching web development, I have learned about a very large number of things to varying degrees. To name a few, I have learned about ReactJS, HTML and CSS fundamentals, JavaScript, MongoDB, and  common data structures and algorithms used to solve coding problems. There are many more things that I have learned about throughout my time researching the world of web development that could be an essay itself.
         </p>
         <p>
            My plans towards progressing towards my career are to continue to work on my software development projects, and research job requirements for a lot of companies so I can tailor what I am learning about to hirable skills. For instance, I will be doing more research into SQL and relational database structuring as my own current experience is document-based NoSQL databases. Additionally, I will be working on my first full stack application to improve my skills and become hirable as a full stack developer instead of just a front-end developer.
         </p>
         <a href="#quicknav" className={styles.back_to_top}>Back to top</a>
         <h1 id="project-management-plan">Project Management Plan</h1>
         <p>
            This essay will cover the specific implementation plan of a software-tracking database for a college. This database will be used and maintained by the IT department of the institution. There are six steps that will be the guiding principles for the implementation plan. In start to finish order they are the initiation phase, definition phase, design phase, development phase, implementation phase, and follow-up phase. Basic information about each software must be available such as the type, the developer, different versions, the types of licensing agreements, what departments use it, the computers in the departments on which the software is installed, and the installation dates. The stakeholders in this scenario are the IT department of the college, as well as those who will use it that are outside of the IT department for various reasons.
         </p>
         <p>
            Starting off with the initiation phase, the database will be a Microsoft Excel database. This is because it is cost effective, simple for people to understand, and easily learnable/editable by the members working on it. The team consisting of the development process will be 5 people, me included. The database will have a user interface tab where the audience will be able to query the database depending on the parameter they are looking for. This will make the database user friendly to a wide range of audiences due to Excel being extremely widespread in its understanding. The user interface tab will also include instructions for how to use it for those who are not previously exposed to Excel.
         </p>
         <p>
            Moving onto the definition phase, the excel database will be organized so that each specific software will have its own row in the database, and each column will be the basic information specified in the introduction. This project will have to remain within the bounds of Excel due to XLSX being a very specific format that isn&apos;t accepted by all platforms. In addition, Excel is an extremely widespread software that many people are familiar with, promoting ease of usability. The database itself will be accessible via a shared document to each member of the staff who needs access to it.
         </p>
         <p>
            Moving on to the design phase, there will be three major components. That will be the user interface, the user query, and the actual database. The user interface will send a request based on the query, the query will then be processed in the background, then the specific queried section of the database will be returned to the user interface as a response. Below is a simple diagram of the process.
         </p>
         <img src="/Picture1.png"></img>
         <p>
            Transitioning into the development phase, all members on the team will be organized, and a timeline will be broken down into phases. All computers that will be worked on for the development process of the database will be selected. Two of the four other members will be assigned to collect the actual data for the database, and the other two will be responsible for programming and designing the actual database. I will act as a supporting role for both groups when deemed necessary and provide oversight.
         </p>
         <p>
            Upon arriving at the implementation phase, the database will be actively being developed, including programmatic features will be written in Visual Basic (VBA). The two collectors will be traveling to each department and actively gathering information, populating and updating database fields with each new list of information they receive. I will be regularly checking in on the progress of both the programmers/designers and the data collectors, making sure that the project is staying on track and heading towards being finished within a reasonable timeframe.
         </p>
         <p>
            Finally, the follow-up phase will include brief training for people who will be regularly using the database for any necessary purposes and making sure that the functionality of the database works clearly, and that error handling is present. We will also allow stakeholders to give us feedback on their experience using the database when they are being trained. This will give us insight as to whether our product came out as desired or not. Last, I will also ask the head of the IT department to contact me if there are any troubles that they run into with the database, as well as providing special training to them to show them how to update the database itself and allow them to determine who needs to be trained for that role.
         </p>
         <p>
            In conclusion, the database implementation plan is divided into six steps, with each section laid out in specific detail as to the process of creating the database. This originates all the way from it just being an idea, to the follow-up process after the database has been developed. Since the database itself is quite simple in its architecture and actual process, it is versatile to more nuanced and specific details that this implementation plan potentially overlooks.
         </p>
         <a href="#quicknav" className={styles.back_to_top}>Back to top</a>
         <h1 id="event-report-1">Event Report</h1>
         <p>
            For this event report, I watched a JSConf lecture. JSConf is an organization that hosts conferences around the world for the sole purpose of talking about JavaScript. There are currently 18 locations that JSConf is hosted. This specific conference was held in Budapest. The main speaker is a man named Kilian Valkhof, who has over 20 years of experience in making web applications. I attended this conference via YouTube on October 1, 2024. The duration of the lecture is 33 minutes and 50 seconds. The main point of the lecture is to discuss the ways developers can go about doing something they would normally perform in JavaScript, but instead doing it in CSS and HTML.
         </p>
         <p>
            The first thing that Kilian covers is making a simple switch GUI with only CSS and HTML instead of JavaScript. A switch is a button you click to disable or enable a setting, that have the appearance of a circle moving to the left or right, as well as a background color, indicating whether the switch is set to enabled or disabled. Switches are common in iPhone settings when you want to enable or disable something. In the live example, Kilian uses the HTML checkbox method to handle state of whether the switch is enabled or disabled. To handle the actual implementation of the GUI, Kilian utilizes the CSS ::before pseudo-element, which inserts something before the actual element itself. Then, he puts the appearance none for the raw HTML input as none. This means that only the switch GUI will be visible and not the checkbox. Next, Kilian adds the :checked pseudo-class, which means you can apply a certain style to something if an associated element is checked. Since the checkbox is wrapped inside the label HTML element, the entire element can dictate the state of the checkbox being checked or not, not just the checkbox. When the switch item is checked, the ::before element translates the circle to the right and the background is changed to green, making it appear as if it is enabled. Last, Kilian adds accessibility features such as the :focus-visible pseudo-class that displays an outline if the user tabs onto the actual input.
         </p>
         <p>
            In a couple smaller examples, he discusses the use of data list and color element in HTML. Data list is useful because it can be used to auto-populate an input field if a user is hypothetically searching for something. This is nice for certain aspects such as adding a search feature to your website. You could hypothetically automatically generate a data list that is a linear array of all items that are searchable, and then the users query will search for pattern matching in the data list. By doing so, the user will be prompted to select an item from the data list that matches their query. Then you can add functionality as you desire once the user selects the data list item. Moving on to the color field, this is nice because it allows you to enable the user to select the specific color of something they may be filling out in say a form. For example, if a user is adding an event to a calendar, adding a color field would be great because you&apos;re enabling the user to determine the color of the item they are adding to the calendar.
         </p>
         <p>
            Another notable thing that Kilian covers is the HTML details element. This is useful because it is a built-in accordion type element which expands into view specific content when the user clicks the details element summary. This element is also useful because it is quite tedious and lengthy to implement in JavaScript, so having it as a built-in browser function saves a ton of time. I personally have used this element a lot in a recent project and have found it to be extremely useful and easy to set up and configure with CSS.
         </p>
         <p>
            The last thing worth touching on is the HTML dialog box. The dialog box is essentially used to display a popup box on the page once a user event happens, such as submitting a form. This element is useful because the browser automatically adds a new thing called a “top layer”. This top layer makes it so that it automatically has the highest z-index visibility and makes the opacity of the web page slightly dark to put emphasis on the dialog box itself. This is an element I have yet to utilize but will plan on using in projects in the future.
         </p>
         <p>
            This JSConf event was quite insightful in teaching ways to utilize the power of raw HTML, CSS, and the browser to do things that many would think could only be done in JavaScript. The methods discussed in the lecture will help save tons of time for specific feature implementations to be made to my web applications. Overall, I found this lecture to be very educational and give me a new perspective on trying to see if it is possible to implement a feature in raw HTML and CSS before going straight to JavaScript.
         </p>
         <a href="https://www.youtube.com/watch?v=IP_rtWEMR0o">View Event</a>
         <br />
         <a href="#quicknav" className={styles.back_to_top}>Back to top</a>
         <h1 id="ethical-case-study">Ethical Case Study Analysis</h1>
         <p>
            The Internet of Things (IoT) are electronic devices that can connect to the Internet in some way. These devices can range from apple watches to speakers. Often associated with the label of “smart” technology. The IoT continues to grow increasingly ubiquitous as developments are made in the field of technology very regularly. Additionally, companies seek to capitalize on making as many IoT related products as possible. Millions of households across the US have various IoT devices that are incorporated into their daily life. Is this entirely a good thing though? For example, having more things tracking data relating to you means that hackers can obtain more information on you if you are a victim of a cybercrime. The following essay will address some valid concerns that come with having a wide range of IoT devices in your home, and possibly provide a new perspective to consider when choosing to increase the quantity of IoT devices incorporated into your daily life.
         </p>
         <p>
            Calling back to the introductory example, the increase in amount of IoT devices absolutely has led to the increase in cyber-attacks. As Check Point Research (2024) highlights in its article, “the first two months of 2023 have seen a 41% increase in the average number of weekly attacks per organization targeting IoT devices, compared to 2022”. These attacks varied across all different types of organization sectors such as education, ISP’s, government, and even retail. Despite the data showing only the growth of attacks made on organizations, it is very reasonable to assume that the number of cyber-attacks has also increased for homeowners. In summary, the increase of IoT devices in your household or organization is very likely to lead to a higher probability of being attacked since there are more avenues for hackers to attack.
         </p>
         <p>
            Another concern that could arise is discussed in the Brookings article discusses how the increase of IoT can lead to rise in surveillance. As Karston (2016) quotes James Clappers testimony to Congress, “in the future, intelligence services might use the IoT for identification, surveillance, monitoring, location tracking, and targeting for recruitment, or to gain access to networks or user credentials”. However, the section of the article goes on to make the argument that IoT simply just adds “more hay than needles” to the metaphorical haystack of amount of IoT devices that would require surveillance. While this conclusion is true, what is concerning about adding more hay to the haystack is that there is more hay being monitored in the first place. The main public concern with surveillance is that they want less hay being monitored, as each aspect of the hay contains data about individuals that they may want to keep private. For example, your smart watch tracks your location. While this may be used as an avenue for surveillance of a potential threat, those that do not pose any threat may feel distrustful of the government knowing that they may be actively monitored without their consent. Essentially, the conclusion is the same as the prior paragraph, but instead of more avenues for attack, it IoT enables more avenues for nonconsensual surveillance.
         </p>
         <p>
            Fortunately, there are solutions for both potential concerns. First, while having more IoT devices does allow for a greater avenue of attack, there are steps you can take to mitigate the actual probability of a specific device being attacked. There are many guides online that go over ways to protect your various IoT devices. Therefore, simply performing some research into IoT security that you can do as an individual is all that is necessary to help mitigate the risk of attack. Second, to address nonconsensual surveillance, then you should take various factors into consideration when purchasing new devices for your home. For example, does the device have voice or speech recognition or “active listening” mechanics? Does the device have a camera on it? Does this device have some form of AI attached to it that picks up on your behaviors? These are just some examples of questions to ask when purchasing devices. An individual’s tolerance of being surveyed via their IoT devices will vary on a case-by-case basis. Therefore, asking questions to yourself such as these will help determine your tolerance of potential surveillance you may be a part of. The answers arrived at will help drive the decision made on what specific IoT devices to purchase, and what ones to not.
         </p>
         <p>
            In conclusion, the degree of IoT you choose to have in your home is determined by your tolerance for things such as potential surveillance, and increased avenues of being attacked. However, when thought about critically, and considering the recommendations discussed in this essay, these potential concerns can be mitigated. It is ideal to have a foundational understanding of your preferences and boundaries of IoT’s involvement in your life as the number of devices that are created continue to grow, and the number of homes that contain them also increase.
         </p>
         <a href="#quicknav" className={styles.back_to_top}>Back to top</a>
         <h1 id="information-policy-in-news">Information Policy/Technology in the News</h1>
         <p>
            The information policy topic this essay will be covering is ACM’s statement regarding responsible algorithmic systems. For better understanding, algorithmic systems usually are something built with an artificial intelligence (AI) foundation underneath it. For example, a Tesla’s self-driving mode would be considered an algorithmic system as it uses AI in its decision-making process. The statement covers how organizations making these types of systems place high emphasis on setting up protocol for how decisions by the system are made, considering things such as the rights of individuals. I believe that ACM hits the nail on the head in that algorithmic systems need to consider certain things that humans consider when decision making. Otherwise, it can lead to a public outrage against algorithmic systems being integrated into the public, as they will claim that they do not think that the systems do not make decisions in a morally correct manner.
         </p>
         <p>
            There are potential legislative implications that are associated to the problem of establishing responsible algorithmic systems. This is due to two reasons major reasons that come to mind. For one, the evolution of algorithmic systems is rapid due to the continuous improvements made on various AI models around the world. Secondly, there is just a lack of concrete legislation that is adopted on a national or even international level regarding policies related to algorithmic systems. As Wright (2023) explains, “over the past five years, 17 states have enacted 29 bills that focus on AI regulation align with these principles”. While this is a good start, it is not nearly enough in terms of how much legislation should exist regarding algorithmic systems.
         </p>
         <p>
            There are a few groups of stakeholders in relation to algorithmic systems which are the developers, consumers, and law makers. The developers and law makers are the biggest stakeholders though, as it is law makers job to make policies and guidelines, and the developer’s job to follow them. If the law makers do not continuously pass more legislation relating to AI, then there will be a lack of clear principles that developers will have to adhere to when creating newer and more widespread algorithmic systems. As a result, consumers can be affected negatively if the device they are using has an algorithmic system that does not have adhere to any principled guidelines or policies. This ties back into the entire point of why the ACM released their statement. It is a general guideline of principles for developers and even law makers to consider when it comes to the subject matter of algorithmic systems and their continued development.
         </p>
         <p>
            There are solutions being worked on to help address the problems raised with algorithmic systems not being fully considered responsible. First, the White House has a blueprint for an AI bill of rights that anyone can go and view for themselves. However, it is important to note that these are all recommendations and not actual legislation as of the time of writing this. It essentially is a more in-depth version of ACM’s statement for guidelines. Secondly, there is a continuous growth of legislation that is getting passed or in the process of being passed. As Associates (2024) states, “we’re currently tracking 616 bills in 45 states (plus another 108 congressional bills) related to AI this year, 40 of which have been enacted into law”. Henceforth, more and more legislation will continue to be passed due to algorithmic systems becoming more ubiquitous and regularly connected to daily lives.
         </p>
         <p>
            Algorithmic systems and AI have been on a monstrous rise in popularity across the recent years, however this does come with some drawbacks. For one, it has been difficult for adequate legislation to be passed to establish guidelines or principles for developers of these systems to adhere to. However, there are solutions that are on the horizon, and a growing number of guidelines from reputable sources and official legislation is being passed around the country to help address the issue presented by algorithmic systems being potentially irresponsible in their decision making. As time continues, a greater number of resources and guidelines will be put in place either through literature or legality for developers to follow when it comes to making responsible algorithmic systems that make moral and logical decisions.
         </p>
         <a href="#quicknav" className={styles.back_to_top}>Back to top</a>
         <h1 id="event-report-2">Event Report 2</h1>
         <p>
            For this event report, I once again decided to attend a JSConf event. This one is discussing what new features are coming to JavaScript. The speaker is Nicolo Ribaudo, an employee at Igalia and TC39 delegate, created the Babel compiler and has worked on several proposals made to JavaScript in the past. This conference was held in Budapest from June 26th – 28th 2024. This essay will go over summarizing the different features that could be coming to JavaScript discussed by Nicolo.
         </p>
         <p>
            Before fully delving into the new features, Nicolo discusses how standard bodies are decided on the web. He uses an example of the various emojis of a hamburger used by different companies. A standard body would mean that all companies use the same burger emoji. There are various organizations that create these standards such as WHATWG, W3C, IETF, ECMA and Unicode. Nicolo then goes on to discuss what TC39 is in more depth. Essentially, it is a technical committee that defines the ECMAScript language. There are 55 committees overall. There are several different categories of participants in these committees such as companies and universities that implement the features proposed as well as subject matter experts and community representatives. Nicolo then goes on to discuss how implementing these new features works. However, I won’t delve into it too much as the focal interest of this event is to discuss the new features coming to JavaScript.
         </p>
         <p>
            At around 13 minutes into the lecture, Nicolo begins to discuss new standards being introduced into ES2024. The first feature is Unicode related utilities. This means that it will check if your string has any lone surrogates and returns a boolean value based on if this condition is true or false. To oversimplify, a lone surrogate is a 16-bit code unit that is in the range of specific UTF code points, and either the next or previous code unit is not a trailing or leading surrogate.
         </p>
         <p>
            Another feature Nicolo discusses deals with raw memory and multi-threading as well as a convenient method for objects or maps called groupBy. This method is very fascinating as it allows you to group arrays by a certain category. This is extremely useful because it used to have to be done much more by hand, for example the filter function comes into mind as to how I would approach the same functionality as groupBy. However, groupBy is easier for specific use cases. For example, Nicolo has an array of objects, each object has a name and a country. With the groupBy method, you can specify the way to group the objects by one of the properties as the second argument. In the example he does groupBy on the country property. So what returns is an object with two separate arrays, one for Italy and one for Germany. This function is useful for specific use cases when it comes to providing a specific view of a list.
         </p>
         <p>
            Some of the other noteworthy features discussed in this lecture from Nicolo are the changes being made to the date constructor, set methods, import attributes and JSON imports, module declarations, decimals, and message formats. Out of these, I am most interested in the date constructor changes. This is because the date constructor is annoying to work with sometimes, specifically when it comes to trying to format it to your desire. For example, if you do the getMonth method, months start from zero instead of 1, so you must do getMonth() + 1. The changes coming will help to make the date constructor more useable and easier to work with.
         </p>
         <p>
            Overall, this conference has shown me things to look forward to that are coming to JavaScript. I regularly use JavaScript myself as I am a software developer, so this lecture I was particularly passionate about. The one that stuck out to me the most was the groupBy method, as it is a large quality of life improvement to save lines of code spent prior to the methods existence trying to achieve the same outcome.
         </p>
         <a href="https://www.youtube.com/watch?v=tKHdASf_OOI">View Event</a>
         <br />
         <a href="#quicknav" className={styles.back_to_top}>Back to top</a>
         <h1 id="program-review">Program Review</h1>
         <p>
            For this assignment I will be discussing upper-level courses that I have completed or am currently completing and their relevance to my future career aspirations. The list of courses that will be discussed in this essay include LIS 3261 Intro to Information Science, LIS 3353 IT Concepts/Info Professionals, LIS 4414 Information Policy and Ethics, LIS 4204 Information Behaviors, LIS 4934 BSIS Senior Capstone, LIS 3361 WWW Page Design/Management, LIS 4482 Networks & Communication, LIS 3352 Interaction Design, LIS 3783 Information Architecture.
         </p>
         <p>
            Starting with LIS 3261 Intro to Information Science, this class helped me establish a foundation for what information science is and how it applies to the real world. This helped me to better understand the framework of information science and apply it to my software development process. LIS 3353 IT Concepts/Info Professionals was another foundational class that covers things such as programming basics, networks, the Internet, and emerging technologies. I found this class useful as it taught me terminology that I still use to this day. LIS 4414 Information Policy and Ethics discusses issues related to cybersecurity and technology development as used in the world today. This class was great because I was unaware how much consideration must be put into policy when it comes to working among organizations. LIS 4402 Information Behaviors was a class that explained the way people behave when it comes to seeking, consuming, and applying information in their lives. I found this class helpful as it helped me to analyze my own approach to my behaviors regarding information seeking and adjust them to a more well thought out approach.
         </p>
         <p>
            LIS 4934 BSIS Senior Capstone has been a great class so far as I have gotten to perform research projects and essays related to my career. This is great because it is nice to have a class that allows you to tailor your research and writing assignments to exactly what you are looking for in a career. LIS 3361 WWW Page Design/Management was a class that covered the basics of making and deploying a website to the web via an FTP program FileZilla. This class was a nice refresher on HTML/CSS, and I gained a better understanding of FTP. LIS 4482 Networks & Communication is a class that covers things such as the TCP/IP Protocol Suite. This class has been great in informing me about network architecture and how things are transferred across the network. LIS 3352 Interaction Design was a class that focused on the importance of user experience when it comes to designing products. This class has been useful for helping me to consider the things that go into making effective UI/UX when it comes to making web applications. Finally, LIS 3783 Information Architecture teaches you the importance of the way information is structured on things such as websites. This has been great in helping me consider the general architecture I want to use when it comes to making website pages.
         </p>
         <p>
            This assignment I was able to cover my higher-level courses that I think have helped me a lot. From each of these classes, I have gained new experiences and knowledge that will shape how I approach my career going forward. They have also helped me build a foundational knowledge that will allow me to have a strong start as I enter the workforce as a college graduate.
         </p>
         <a href="#quicknav" className={styles.back_to_top}>Back to top</a>
         <h1 id="program-review-2">Program Review 2</h1>
         <p>
            This essay will discuss three assignments that I have completed, one of those I’m still actively working on, and their importance to me and my future career aspiration as a software developer. The first assignment is the website that I am currently working on for my senior capstone class LIS 4934. The second assignment is a semester long assignment for my web design and management class LIS 3361. The third assignment is from job search SLS 3308, in which I made a final draft of my resume.
         </p>
         <p>
            First, let’s discuss the senior capstone assignment that I am still currently working on. It is a semester long project in which we are required to make an e-portfolio and deploy it to the web for others to view. The e-portfolio is our own website which includes things such as information about us, assignments completed throughout the semester, contact information, and our resume for others to view. We slowly add artifacts to it each week throughout the semester. This project I find important because it allows me to gain additional practice what I plan to do for a full-time job as an actual assignment. I coded my portfolio by hand so it encourages me to gain a better understanding of various technologies I will work with regularly in my career.
         </p>
         <p>
            My second assignment I found important to me is my web design and management classes semester long website assignment. It is very similar to the e-portfolio assignment, however the actual content on the website was different. It included various things that were more related to layout rather than actual content on it. For example, we had to incorporate an Iframe somewhere on the page, an image map, and other things that I was unfamiliar with when it came to web development. This assignment was important because it introduced me to new concepts that I had not worked with yet when it came to web development. This is why I found the assignment important, as I gained experience with new concepts and ideas related to HTML that I had not yet worked with.
         </p>
         <p>
            My third assignment that I want to discuss is my final resume for my job search class. The assignment had an initial rough draft, and then we received feedback and applied it to our final assignment. My initial assignment had a good score, but there was much to improve on. The professor highlighted things that I needed to adjust in my resume, such as actin bullet points, and overall layout of my resume. This assignment I found very useful as it allows me to have a more professionally formatted resume to submit to companies seeking employees.
         </p>
         <p>
            In conclusion, these three assignments were very impactful on me, and I found them applicable to my future career aspirations. However, there are even more assignments that I found useful regarding learning about various new topics, even if they weren’t quite as applicable to my future career. For example, I did an assignment related to active defense of companies that I found very interesting, and it was very insightful. Regardless, the three assignments discussed in this essay stuck out to me as the most important in relation to my career aspirations above other ones that I have completed. The skills gained in them will serve me well in my career down the road.
         </p>
         <a href="#quicknav" className={styles.back_to_top}>Back to top</a>
         <h1 id="reflection-essay">Reflection Essay</h1>
         <p>
            The duration of my studies in the realm of information sciences has helped me grow as an individual in various forms that will benefit me for the duration of my career. Various courses such as information behaviors, website design and management, information architecture, local area networks and concepts, and more have helped me establish a foundational knowledge of the subject field that I will apply to my practice of being a software developer.
         </p>
         <p>
            Coursework across various courses relating to information science has helped me gain an understanding of the various areas across the field. For example, classes like information architecture have helped me shape the way I would go about making websites so that the navigability, design, and architecture of the website promotes a nice user experience overall. Another example that is more personal is information behaviors taught me how people interact with information, and the general behaviors they carry out when seeking it. This helped me in performing a meta-analysis on the way I seek information and consider ways to improve it. A third would be local area network concepts, which has helped me greatly in terms of learning about various internet protocols within the TCP/IP protocol suite. Overall, the courses and various assignments that I have completed in the information science program at USF have helped me prepare for work in my career field by providing me with various foundational knowledge that I will need to work as a software developer.
         </p>
         <p>
            There are many aspects of the program that I enjoyed, and a small amount that I disliked. Addressing the dislike first, I wish there were more programming related classes. However, the degree I pursued was information science and not computer science since the concentration for web development is fell under information science only. Some more overlap with courses offered in the computer science program would have been beneficial for me personally, such as the data structures and algorithms course. Moving on to things that I like about the information science program, I did enjoy the various classes that forced me to analyze the flow of information on a website, and how to construct it to have a highly optimized layout to improve the overall user experience. I also enjoyed the meta-analysis aspects of classes such as information behaviors, interaction design, and others that helped me to analyze my own thinking patterns internally and help me improve myself and how I interact with and process information.
         </p>
         <p>
            As of now, I do not currently plan to pursue additional education regarding the field of information science. In general, the field of software development is only seeking a bachelor’s degree. Very few are requiring a higher degree of education. Regarding suggestions for the program, I would consider implementing more programming related classes into web development such as ones discussed previously, or just moving the web development concentration into the computer science program rather than information science.
         </p>
         <p>
            Overall, I have thoroughly enjoyed my time in the information science program at USF. The courses have helped me develop a foundational knowledge across various aspects of the field that I will carry with me for the remainder of my career. While there are some things that I would change about the web development concentration specifically, I do think that this does not detract from the valuable education I gained during my time in the information science program.
         </p>
         <a href="#quicknav" className={styles.back_to_top}>Back to top</a>
      </main>
   )
}