import styles from "./artifacts.module.scss";

export default function Artifacts() {
   return (
      <main className={styles.artifacts_main}>
         <h1>Career Aspirations Essay</h1>
         <p>
            My major area of study is information science with a concentration in web development. This major is relevant to my career aspiration. My career aspiration is to become a software developer of some kind. This can be either a front-end developer or a full stack developer. I am not too particular on which one, as I enjoy both the front-end side and full stack side of the development process of web applications. This is the role I envision myself working in in my upcoming future career. The origins of how I became passionate about web development goes back to when I was in 7th grade. I took my first web design class, and I knew by taking that class I was going to do that for a career. It was a fascinating thing to make a website purely by hand and I really enjoyed the creative process that went into it as well.
         </p>
         <p>
            I do have brief work experience in web development. When I worked for Westlake Christian School, I worked alongside someone to help add content to the school&apos;s website. The school used a CMS provider called FACTS to host their website. My job was to go through the CMS and add relevant content depending on the request of my manager. My non-work experience related to web development is the various projects I have made and host the source code on my GitHub account.
         </p>
         <p>
            Prior to this assignment, I had not visited the USF career services website. However, I do find this website useful after visiting. It has a wide range of resources available for students’ seeking information or opportunities to browse. The most interesting aspect to me is the career fairs that they have going on. This is appealing because I have yet to go to one, but they do seem like a great opportunity for those who are looking to meet directly with employers and other alike minds trying to work for a company. Therefore, I do plan on attending one of these for Technology and Engineering in the future.
         </p>
         <p>
            I do have various internship experiences dating all throughout my duration at college and even high school. As mentioned, prior, I did an internship as a web developer at Westlake Christian School. I was eventually added as an employee and did database management for them for around another year until December 2023. Another internship I did was at Lockheed Martin. I completed it through a dual enrollment class my senior year of high school called the executive internship program. During my time there, I helped them with database management for parts used in the development areas, as well as organizing physical stencil boards and SMT parts. Regarding other actual jobs, I have worked at Publix as a customer service employee since 2016 when I was 14 years old, and currently still work there today. Additionally, I have also worked as an invoice specialist for Label IT technologies for over a year now. I work these two jobs simultaneously as well as attending USF.
         </p>
         <p>
            I have done a very length amount of research into the world of web application development. There are tons of resources I utilize such as W3schools, FreeCodeCamp, GeeksForGeeks, and many more. I have also taken an extensive number of notes on things such as data structures and algorithms. USF library resources have not been used often for me when it comes to researching for my career, as that usually contains more study related information, whereas I am searching for documentation and tutorials. In my time researching web development, I have learned about a very large number of things to varying degrees. To name a few, I have learned about ReactJS, HTML and CSS fundamentals, JavaScript, MongoDB, and  common data structures and algorithms used to solve coding problems. There are many more things that I have learned about throughout my time researching the world of web development that could be an essay itself.
         </p>
         <p>
            My plans towards progressing towards my career are to continue to work on my software development projects, and research job requirements for a lot of companies so I can tailor what I am learning about to hirable skills. For instance, I will be doing more research into SQL and relational database structuring as my own current experience is document-based NoSQL databases. Additionally, I will be working on my first full stack application to improve my skills and become hirable as a full stack developer instead of just a front-end developer.
         </p>
         <h1>Project Management Plan</h1>
         <p>
            This essay will cover the specific implementation plan of a software-tracking database for a college. This database will be used and maintained by the IT department of the institution. There are six steps that will be the guiding principles for the implementation plan. In start to finish order they are the initiation phase, definition phase, design phase, development phase, implementation phase, and follow-up phase. Basic information about each software must be available such as the type, the developer, different versions, the types of licensing agreements, what departments use it, the computers in the departments on which the software is installed, and the installation dates. The stakeholders in this scenario are the IT department of the college, as well as those who will use it that are outside of the IT department for various reasons.
         </p>
         <p>
            Starting off with the initiation phase, the database will be a Microsoft Excel database. This is because it is cost effective, simple for people to understand, and easily learnable/editable by the members working on it. The team consisting of the development process will be 5 people, me included. The database will have a user interface tab where the audience will be able to query the database depending on the parameter they are looking for. This will make the database user friendly to a wide range of audiences due to Excel being extremely widespread in its understanding. The user interface tab will also include instructions for how to use it for those who are not previously exposed to Excel.
         </p>
         <p>
            Moving onto the definition phase, the excel database will be organized so that each specific software will have its own row in the database, and each column will be the basic information specified in the introduction. This project will have to remain within the bounds of Excel due to XLSX being a very specific format that isn&apos;t accepted by all platforms. In addition, Excel is an extremely widespread software that many people are familiar with, promoting ease of usability. The database itself will be accessible via a shared document to each member of the staff who needs access to it.
         </p>
         <p>
            Moving on to the design phase, there will be three major components. That will be the user interface, the user query, and the actual database. The user interface will send a request based on the query, the query will then be processed in the background, then the specific queried section of the database will be returned to the user interface as a response. Below is a simple diagram of the process.
         </p>
         <img src="/Picture1.png"></img>
         <p>
            Transitioning into the development phase, all members on the team will be organized, and a timeline will be broken down into phases. All computers that will be worked on for the development process of the database will be selected. Two of the four other members will be assigned to collect the actual data for the database, and the other two will be responsible for programming and designing the actual database. I will act as a supporting role for both groups when deemed necessary and provide oversight.
         </p>
         <p>
            Upon arriving at the implementation phase, the database will be actively being developed, including programmatic features will be written in Visual Basic (VBA). The two collectors will be traveling to each department and actively gathering information, populating and updating database fields with each new list of information they receive. I will be regularly checking in on the progress of both the programmers/designers and the data collectors, making sure that the project is staying on track and heading towards being finished within a reasonable timeframe.
         </p>
         <p>
            Finally, the follow-up phase will include brief training for people who will be regularly using the database for any necessary purposes and making sure that the functionality of the database works clearly, and that error handling is present. We will also allow stakeholders to give us feedback on their experience using the database when they are being trained. This will give us insight as to whether our product came out as desired or not. Last, I will also ask the head of the IT department to contact me if there are any troubles that they run into with the database, as well as providing special training to them to show them how to update the database itself and allow them to determine who needs to be trained for that role.
         </p>
         <p>
            In conclusion, the database implementation plan is divided into six steps, with each section laid out in specific detail as to the process of creating the database. This originates all the way from it just being an idea, to the follow-up process after the database has been developed. Since the database itself is quite simple in its architecture and actual process, it is versatile to more nuanced and specific details that this implementation plan potentially overlooks.
         </p>

         <h1>Event Report</h1>
         <p>
            For this event report, I watched a JSConf lecture. JSConf is an organization that hosts conferences around the world for the sole purpose of talking about JavaScript. There are currently 18 locations that JSConf is hosted. This specific conference was held in Budapest. The main speaker is a man named Kilian Valkhof, who has over 20 years of experience in making web applications. I attended this conference via YouTube on October 1, 2024. The duration of the lecture is 33 minutes and 50 seconds. The main point of the lecture is to discuss the ways developers can go about doing something they would normally perform in JavaScript, but instead doing it in CSS and HTML.
         </p>
         <p>
            The first thing that Kilian covers is making a simple switch GUI with only CSS and HTML instead of JavaScript. A switch is a button you click to disable or enable a setting, that have the appearance of a circle moving to the left or right, as well as a background color, indicating whether the switch is set to enabled or disabled. Switches are common in iPhone settings when you want to enable or disable something. In the live example, Kilian uses the HTML checkbox method to handle state of whether the switch is enabled or disabled. To handle the actual implementation of the GUI, Kilian utilizes the CSS ::before pseudo-element, which inserts something before the actual element itself. Then, he puts the appearance none for the raw HTML input as none. This means that only the switch GUI will be visible and not the checkbox. Next, Kilian adds the :checked pseudo-class, which means you can apply a certain style to something if an associated element is checked. Since the checkbox is wrapped inside the label HTML element, the entire element can dictate the state of the checkbox being checked or not, not just the checkbox. When the switch item is checked, the ::before element translates the circle to the right and the background is changed to green, making it appear as if it is enabled. Last, Kilian adds accessibility features such as the :focus-visible pseudo-class that displays an outline if the user tabs onto the actual input.
         </p>
         <p>
            In a couple smaller examples, he discusses the use of data list and color element in HTML. Data list is useful because it can be used to auto-populate an input field if a user is hypothetically searching for something. This is nice for certain aspects such as adding a search feature to your website. You could hypothetically automatically generate a data list that is a linear array of all items that are searchable, and then the users query will search for pattern matching in the data list. By doing so, the user will be prompted to select an item from the data list that matches their query. Then you can add functionality as you desire once the user selects the data list item. Moving on to the color field, this is nice because it allows you to enable the user to select the specific color of something they may be filling out in say a form. For example, if a user is adding an event to a calendar, adding a color field would be great because you&apos;re enabling the user to determine the color of the item they are adding to the calendar.
         </p>
         <p>
            Another notable thing that Kilian covers is the HTML details element. This is useful because it is a built-in accordion type element which expands into view specific content when the user clicks the details element summary. This element is also useful because it is quite tedious and lengthy to implement in JavaScript, so having it as a built-in browser function saves a ton of time. I personally have used this element a lot in a recent project and have found it to be extremely useful and easy to set up and configure with CSS.
         </p>
         <p>
            The last thing worth touching on is the HTML dialog box. The dialog box is essentially used to display a popup box on the page once a user event happens, such as submitting a form. This element is useful because the browser automatically adds a new thing called a “top layer”. This top layer makes it so that it automatically has the highest z-index visibility and makes the opacity of the web page slightly dark to put emphasis on the dialog box itself. This is an element I have yet to utilize but will plan on using in projects in the future.
         </p>
         <p>
            This JSConf event was quite insightful in teaching ways to utilize the power of raw HTML, CSS, and the browser to do things that many would think could only be done in JavaScript. The methods discussed in the lecture will help save tons of time for specific feature implementations to be made to my web applications. Overall, I found this lecture to be very educational and give me a new perspective on trying to see if it is possible to implement a feature in raw HTML and CSS before going straight to JavaScript.
         </p>
         <p>
            <a href="https://www.youtube.com/watch?v=IP_rtWEMR0o">View Event</a>
         </p>
         <h1>Ethical Case Study Analysis</h1>
         <p>
            The Internet of Things (IoT) are electronic devices that can connect to the Internet in some way. These devices can range from apple watches to speakers. Often associated with the label of “smart” technology. The IoT continues to grow increasingly ubiquitous as developments are made in the field of technology very regularly. Additionally, companies seek to capitalize on making as many IoT related products as possible. Millions of households across the US have various IoT devices that are incorporated into their daily life. Is this entirely a good thing though? For example, having more things tracking data relating to you means that hackers can obtain more information on you if you are a victim of a cybercrime. The following essay will address some valid concerns that come with having a wide range of IoT devices in your home, and possibly provide a new perspective to consider when choosing to increase the quantity of IoT devices incorporated into your daily life.
         </p>
         <p>
            Calling back to the introductory example, the increase in amount of IoT devices absolutely has led to the increase in cyber-attacks. As Check Point Research (2024) highlights in its article, “the first two months of 2023 have seen a 41% increase in the average number of weekly attacks per organization targeting IoT devices, compared to 2022”. These attacks varied across all different types of organization sectors such as education, ISP’s, government, and even retail. Despite the data showing only the growth of attacks made on organizations, it is very reasonable to assume that the number of cyber-attacks has also increased for homeowners. In summary, the increase of IoT devices in your household or organization is very likely to lead to a higher probability of being attacked since there are more avenues for hackers to attack.
         </p>
         <p>
            Another concern that could arise is discussed in the Brookings article discusses how the increase of IoT can lead to rise in surveillance. As Karston (2016) quotes James Clappers testimony to Congress, “in the future, intelligence services might use the IoT for identification, surveillance, monitoring, location tracking, and targeting for recruitment, or to gain access to networks or user credentials”. However, the section of the article goes on to make the argument that IoT simply just adds “more hay than needles” to the metaphorical haystack of amount of IoT devices that would require surveillance. While this conclusion is true, what is concerning about adding more hay to the haystack is that there is more hay being monitored in the first place. The main public concern with surveillance is that they want less hay being monitored, as each aspect of the hay contains data about individuals that they may want to keep private. For example, your smart watch tracks your location. While this may be used as an avenue for surveillance of a potential threat, those that do not pose any threat may feel distrustful of the government knowing that they may be actively monitored without their consent. Essentially, the conclusion is the same as the prior paragraph, but instead of more avenues for attack, it IoT enables more avenues for nonconsensual surveillance.
         </p>
         <p>
            Fortunately, there are solutions for both potential concerns. First, while having more IoT devices does allow for a greater avenue of attack, there are steps you can take to mitigate the actual probability of a specific device being attacked. There are many guides online that go over ways to protect your various IoT devices. Therefore, simply performing some research into IoT security that you can do as an individual is all that is necessary to help mitigate the risk of attack. Second, to address nonconsensual surveillance, then you should take various factors into consideration when purchasing new devices for your home. For example, does the device have voice or speech recognition or “active listening” mechanics? Does the device have a camera on it? Does this device have some form of AI attached to it that picks up on your behaviors? These are just some examples of questions to ask when purchasing devices. An individual’s tolerance of being surveyed via their IoT devices will vary on a case-by-case basis. Therefore, asking questions to yourself such as these will help determine your tolerance of potential surveillance you may be a part of. The answers arrived at will help drive the decision made on what specific IoT devices to purchase, and what ones to not.
         </p>
         <p>
            In conclusion, the degree of IoT you choose to have in your home is determined by your tolerance for things such as potential surveillance, and increased avenues of being attacked. However, when thought about critically, and considering the recommendations discussed in this essay, these potential concerns can be mitigated. It is ideal to have a foundational understanding of your preferences and boundaries of IoT’s involvement in your life as the number of devices that are created continue to grow, and the number of homes that contain them also increase.
         </p>
      </main>
   )
}